version: '3.4'

services:

  mysql_server_temporal:
    #Ignorado cuando se usa en modo swarm (swarm usa imágenes de un registry)
    build: ../basedatos/
    image: cemp2703/java-aws-tp-bd
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=demobd
      - MYSQL_ROOT_HOST=%
    volumes: 
      - ../basedatos/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "3310:3306"
    #Ignorado cuando se usa en swarm mode (usar restart_policy)
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password

  apipersona:
    build: ../api-persona/
    image: cemp2703/java-aws-tp-api_persona
    environment: 
      - JAVA_OPTS=""
      - host=mysql_server_temporal
      - port=3306
      - database=demobd
      - username=root
      - password=12345678
    depends_on:
      - mysql_server_temporal
    #Si no especifico un puerto host, se creará uno aleatorio
    ports:
    - "8081:8080"
    restart: on-failure
    #Sobreescribiendo el entrypoint del dockerfile
    entrypoint: java -jar /workspace/app.jar

  apipreferencia:
    build: ../api-preferencia/
    image: cemp2703/java-aws-tp-api_preferencia
    environment: 
      - JAVA_OPTS=""
      - host=mysql_server_temporal
      - port=3306
      - database=demobd
      - username=root
      - password=12345678
      - url_apipersona=apipersona
      - port_apipersona=8080
    depends_on: 
      - mysql_server_temporal
      - apipersona
    ports:
       - "8082:8080"
    restart: on-failure
    entrypoint: java -jar /workspace/app.jar

volumes:
  my-data: